# Generated by Django 4.0.6 on 2024-11-24 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(choices=[('Area1', 'Area1'), ('Area2', 'Area2')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(choices=[('Jefe RR.HH', 'Jefe RR.HH'), ('Personal RR.HH', 'Personal RR.HH'), ('Trabajador', 'Trabajador')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_departamento', models.CharField(choices=[('Departamento1', 'Departamento1'), ('Departamento2', 'Departamento2'), ('Departamento3', 'Departamento3'), ('Departamento4', 'Departamento4')], max_length=30)),
                ('area_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.area')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(null=True)),
                ('cargo_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.cargo')),
                ('departamento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.departamento')),
                ('persona_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registro.persona')),
                ('user_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('relacion', models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hijo', 'Hijo'), ('Hija', 'Hija'), ('Esposo', 'Esposo'), ('Esposa', 'Esposa'), ('Hermano', 'Hermano'), ('Hermana', 'Hermana'), ('Abuelo', 'Abuelo'), ('Abuela', 'Abuela'), ('Nieto', 'Nieto'), ('Nieta', 'Nieta'), ('Tío', 'Tío'), ('Tía', 'Tía'), ('Sobrino', 'Sobrino'), ('Sobrina', 'Sobrina'), ('Primo', 'Primo'), ('Prima', 'Prima'), ('Otro', 'Otro')], max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('trabajador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='CargaFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=30)),
                ('parentesco', models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hijo', 'Hijo'), ('Hija', 'Hija'), ('Esposo', 'Esposo'), ('Esposa', 'Esposa'), ('Hermano', 'Hermano'), ('Hermana', 'Hermana'), ('Abuelo', 'Abuelo'), ('Abuela', 'Abuela'), ('Nieto', 'Nieto'), ('Nieta', 'Nieta'), ('Tío', 'Tío'), ('Tía', 'Tía'), ('Sobrino', 'Sobrino'), ('Sobrina', 'Sobrina'), ('Primo', 'Primo'), ('Prima', 'Prima'), ('Otro', 'Otro')], max_length=20)),
                ('trabajador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.trabajador')),
            ],
        ),
    ]
