# Generated by Django 4.0.6 on 2024-11-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_cargafamiliar_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='contraseña_cambiada',
            field=models.BooleanField(default=False),
        ),
    ]
